#!/bin/bash

# pip Installation script

pip3 install attrs
pip3 install Automat
pip3 install blinker
pip3 install certifi
pip3 install cffi
pip3 install chardet
pip3 install charset-normalizer
pip3 install click
pip3 install cloud-init
pip3 install colorama
pip3 install command-not-found
pip3 install configobj
pip3 install constantly             
pip3 install cryptography           
pip3 install dbus-python            
pip3 install distro                 
pip3 install distro-info            
pip3 install entrypoints            
pip3 install eventkit               
pip3 install httplib2               
pip3 install hyperlink              
pip3 install ib-insync              
pip3 install ibapi                  
pip3 install idna                   
pip3 install importlib-metadata     
pip3 install incremental            
pip3 install jeepney                
pip3 install Jinja2                 
pip3 install jsonpatch              
pip3 install jsonpointer            
pip3 install jsonschema             
pip3 install keyring                
pip3 install language-selector      
pip3 install launchpadlib           
pip3 install lazr.restfulclient     
pip3 install lazr.uri               
pip3 install linecache2             
pip3 install Mako                   
pip3 install Markdown               
pip3 install MarkupSafe             
pip3 install more-itertools         
pip3 install nest-asyncio           
pip3 install netifaces              
pip3 install numpy                  
pip3 install oauthlib               
pip3 install packaging              
pip3 install pbr                    
pip3 install pexpect                
pip3 install pip                    
pip3 install ptyprocess             
pip3 install pyasn1                 
pip3 install pyasn1-modules         
pip3 install pycairo                
pip3 install pycparser              
pip3 install PyDbLite               
pip3 install Pygments               
pip3 install PyGObject              
pip3 install PyHamcrest             
pip3 install PyJWT                  
pip3 install pymacaroons            
pip3 install PyNaCl                 
pip3 install pyOpenSSL              
pip3 install pyparsing              
pip3 install pyrsistent             
pip3 install pyserial               
pip3 install python-apt             
pip3 install python-debian          
pip3 install PyYAML                 
pip3 install requests               
pip3 install requests-unixsocket    
pip3 install schedule               
pip3 install SecretStorage          
pip3 install service-identity       
pip3 install setuptools             
pip3 install simplejson             
pip3 install six                    
pip3 install sos                    
pip3 install ssh-import-id          
pip3 install systemd-python         
pip3 install testresources          
pip3 install traceback2             
pip3 install Twisted                
pip3 install typing-extensions      
pip3 install ubuntu-advantage-tools 
pip3 install ufw                    
pip3 install unattended-upgrades    
pip3 install unittest2              
pip3 install urllib3                
pip3 install wadllib                
pip3 install wheel                  
pip3 install zipp                   
pip3 install zope.interface
pip3 install py-spy
pip3 install nuitka
pip3 install pymongo